##
## Quota configuration.
##

# Note that you also have to enable quota plugin in mail_plugins setting.
## <https://doc.dovecot.org/latest/core/plugins/quota.html>

##
## Quota limits
##

# Quota limits are set using "quota_rule" parameters. To get per-user quota
# limits, you can set/override them by returning "quota_rule" extra field
# from userdb. It's also possible to give mailbox-specific limits, for example
# to give additional 100 MB when saving to Trash:

# Postfix compat
quota_status_success = DUNNO
quota_status_nouser = DUNNO

# default message
quota_status_overquota = "552 5.2.2 Mailbox is full / Buzon de correo lleno"

# default if no specified
quota "User quota" {
  # extra 5MB overall
  quota_storage_grace = 5M

  # # 90% of the quota warning
  # warning warn-90 {
  #   quota_storage_percentage = 90
  #   execute quota-warning {
  #     args = 90 %{user}
  #   }
  # }

  # # 75% of the quota warning
  # warning warn-75 {
  #   quota_storage_percentage = 75
  #   execute quota-warning {
  #     args = 75 %{user}
  #   }
  # }
}

# Namespace per mailbox folder
namespace inbox {
   mailbox Trash {
     quota_storage_extra = 10M
   }
}

##
## Quota warnings
##

# You can execute a given command when user exceeds a specified quota limit.
# Each quota root has separate limits. Only the command for the first
# exceeded limit is excecuted, so put the highest limit first.
# The commands are executed via script service by connecting to the named
# UNIX socket (quota-warning below).
# Note that % needs to be escaped as %%, otherwise "% " expands to empty.

quota "User quota" {
  warning warn-90 {
    quota_storage_percentage = 90
    execute quota-warning {
      args = 90 %{user}
    }
  }
  warning warn-75 {
    quota_storage_percentage = 75
    execute quota-warning {
      args = 75 %{user}
    }
  }
}

# Example quota-warning service. The unix listener's permissions should be
# set in a way that mail processes can connect to it. Below example assumes
# that mail processes run as vmail user. If you use mode=0666, all system users
# can generate quota warnings to anyone.
service quota-warning {
  executable = script /etc/dovecot/scripts/quota-warning.sh
  user = dovecot
  unix_listener quota-warning {
    user = dovecot
    mode = 0666
  }
}

##
## Quota backends
##

# Multiple backends are supported:
#   count: Default and recommended, quota driver tracks the quota internally within Dovecot's index files.
#   maildir: Maildir++ quota
#   fs: Read-only support for filesystem quota
#quota "User quota" {
#  driver = count
#}

# net quota status for postfix 
service quota-status {
  executable = quota-status -p postfix
  inet_listener quota-status {
    # You can choose any port you want
    port = 12340
  }
  client_limit = 1
}
